Upstream package updates
Yaskawa-Global/micro_ros_motoplus pull request #4
Opened 2024-07-01 17:58 UTC by jimmy-mcelwain

Updates packages to pull from newer versions for iron

2024-07-01 18:01 UTC, gavanderhoorn commented
Thanks for the PR.

Could you please rebase on `iron_update_20240327`? Your PR contains a couple of changes that would already be part of #3 and the diff is a bit confusing like this.

2024-07-01 18:02 UTC, gavanderhoorn commented
I'm especially confused about 1aa6c57559e16afb6fe9ec7b9f1a4424b83c08d6.

2024-07-01 18:46 UTC, jimmy-mcelwain commented
Alright, I rebased onto `iron_update_20240327`. Hopefully that makes it cleaner.

2024-07-01 19:47 UTC, gavanderhoorn requested changes

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.ignore
> +ros2/rosidl/rosidl_generator_tests
```suggestion
```

not sure what happened here: is this a duplicate of line 37?

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.ignore
> +uros/rosidl_typesupport/rosidl_typesupport_tests
```suggestion
```

duplicate of line 42?

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.ignore
> +uros/tracetools/test_ros2trace
```suggestion
```

duplicate of line 46?

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.repos
> +    version: 63d5c43993cb2d0d03ecd1b68d771046fd4ad19f
I would suggest we keep this as it was. The extra commit only changes CI config in `rclc`: https://github.com/ros2/rclc/commit/63d5c43993cb2d0d03ecd1b68d771046fd4ad19f.

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.repos
> +    # from GCC deprecation attributes used (which GCC in M+ doesn't support))
```suggestion
```

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.repos
> +    version: 4.0.2
Also suggest to revert this: `4.0.2` only updates Doxygen config and some minor content changes.

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.repos
> +  # It does not end up in 'libmicroros.a'
```suggestion
```

2024-07-01 19:47 UTC, gavanderhoorn commented on target_ws_pkgs.repos
> +    version: 0.31.7
we only use `tf2_msgs` from this, and both `0.31.6` and `0.31.7` don't contain any changes to that package ([here](https://github.com/ros2/geometry2/commit/719c3a212480f8f418ba682ba53c623687bb366d#diff-ca78c11f23eece3ef5739c290f99b57bff30c3d7c44e630056580cc52de3701e) and [here](https://github.com/ros2/geometry2/commit/c2b74336100e5a24720dccaac102f181511bd7dd#diff-ca78c11f23eece3ef5739c290f99b57bff30c3d7c44e630056580cc52de3701e)).

2024-07-02 09:30 UTC, gavanderhoorn commented
Thanks @jimmy-mcelwain.

I've squashed your commits (and a single fixup from my side).

2024-07-02 09:30 UTC, gavanderhoorn commented
Could you please let me know which upstream Iron release you took these package versions from?

Then we can update the commit comment (on 0ec37d6db619b93949288d148c33d32ffb57ad63) and merge this.

2024-07-02 15:27 UTC, jimmy-mcelwain commented
I misunderstood, I didn't take the versions from any single release of iron. In many cases I just pulled the latest release for iron from each package individually. I can update it to match a single released version (I will look at [20240423](https://github.com/ros2/ros2/releases/tag/release-iron-20240423)), but to do so I may have to also rebase some of our forked branches onto newer upstream versions, e.g. our fork of [ament_cmake](https://github.com/Yaskawa-Global/ament_cmake/tree/iron-motoplus1-candidate-20240327) is based on 2.0.4 whereas iron release 20240423 targets uses 2.0.5. 

Also, the [micro-ros releases](https://github.com/micro-ROS/micro_ros_setup/releases/tag/4.1.0) don't appear to target specific releases/commits when pulling packages, it just pulls the newest version from each iron branch [if I am reading the .repos file correctly](https://github.com/micro-ROS/micro_ros_setup/blob/iron/config/client_uros_packages.repos). So I may just target the latest released version for each repo that they target if that seems reasonable.

Sorry for the confusion

2024-07-02 15:59 UTC, gavanderhoorn commented
First: lets not make things more complex than they already are. I suggest we keep the list of pkgs you already identified, including the versions in this PR.

Having written that: we loosely follow [calendar versioning](https://calver.org) here, and the fact upstream tags their `.repos` files with something like that should make things easier to keep in-sync. Rationale: (expected) benefits wrt compatibility between (micro)ROS 2 and MotoROS2.

We can't completely limit ourselves to upstream releases as we sometimes need additional (unreleased) fixes.

For future updates we'll want to look at / stick to upstream release tags. For now we'll keep your PR as-is.

2024-07-02 15:59 UTC, gavanderhoorn commented
I suggest we update the commit comment to instead mention the date at which you checked upstream.

2024-07-02 16:07 UTC, gavanderhoorn commented
oh, and to clarify:

> Also, the [micro-ros releases](https://github.com/micro-ROS/micro_ros_setup/releases/tag/4.1.0) don't appear to target specific releases/commits when pulling packages, it just pulls the newest version from each iron branch [if I am reading the .repos file correctly](https://github.com/micro-ROS/micro_ros_setup/blob/iron/config/client_uros_packages.repos?rgh-link-date=2024-07-02T15%3A27%3A20Z). So I may just target the latest released version for each repo that they target if that seems reasonable.

When I write *upstream*, I don't necessarily mean micro-ROS. Technically we use micro-ROS, but quite a few packages come from 'regular' ROS 2.

I should've clarified.

2024-07-02 20:00 UTC, jimmy-mcelwain commented
Okay. I last did a complete check of the upstream branches yesterday, so I marked it as such through the commit message and pushed it back up.

2024-07-09 13:14 UTC, gavanderhoorn commented
Test build: [here](https://github.com/Yaskawa-Global/motoplus_libmicroros_builder/actions/runs/9857358630).

Seems to build. Thanks @jimmy-mcelwain :+1:

2024-07-09 13:48 UTC, gavanderhoorn approved these changes

2024-07-09 13:48 UTC, merged